disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - identifier_name
  - trailing_whitespace
  - line_length
  - variable_name
  - type_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - designTests
  - designUITests